-- 관리자 계정 : somomo계정생성, 권한부여
--create user somomo identified by somomo;
--grant connect, resource to somomo;

--------------------------------------------------
-----------     DROP TABLE/SEQUENCE   	----------
--------------------------------------------------

DROP TABLE CHAT;
DROP TABLE CHAT_MEMBER;
DROP TABLE CHAT_ROOM;

DROP TABLE GROUP_REPLY;
DROP TABLE GROUP_ATTACHMENT;
DROP TABLE GROUP_LIKES;
DROP TABLE GROUP_BOARD;
DROP TABLE CALENDAR_PLAN;
DROP TABLE GROUP_CALENDAR;
DROP TABLE GROUP_JOIN_APPLY;
DROP TABLE GROUP_MEMBER;
DROP TABLE GROUP_ROOM;
DROP TABLE GROUP_CATEGORY;


DROP TABLE FEED_REPLY;
DROP TABLE FEED_ATTACHMENT;
DROP TABLE FEED_LIKES;
DROP TABLE FEED_BOARD;

DROP TABLE REGION_CATEGORY;
DROP TABLE MEMBER;
DROP TABLE CERT;


DROP SEQUENCE SEQ_CRNO; -- CHAT_ROOM
DROP SEQUENCE SEQ_CNO;  -- CHAT
DROP SEQUENCE SEQ_GRNO; -- GROUP_REPLY
DROP SEQUENCE SEQ_GANO; -- GROUP_ATTACHMENT
DROP SEQUENCE SEQ_GBNO; -- GROUP_BOARD
DROP SEQUENCE SEQ_PNO;  -- CALENDAR_PLAN
DROP SEQUENCE SEQ_GCDNO;-- GROUP_CALENDAR
DROP SEQUENCE SEQ_GJANO;-- GROUP_JOIN_APPLY
DROP SEQUENCE SEQ_GNO;  -- GROUP_ROOM
DROP SEQUENCE SEQ_GCNO; -- GROUP_CATEGORY
DROP SEQUENCE SEQ_FRNO; -- FEED_REPLY
DROP SEQUENCE SEQ_FANO; -- FEED_ATTACHMENT
DROP SEQUENCE SEQ_FBNO; -- FEED_BOARD
DROP SEQUENCE SEQ_RCNO; -- REGION_CATEGORY 

--------------------------------------------------
--------------     MEMBER   	------------------
--------------------------------------------------
CREATE TABLE MEMBER(
    USER_ID VARCHAR2(30) PRIMARY KEY,
    USER_PWD VARCHAR2(300) NOT NULL,
    NICKNAME VARCHAR2(30) UNIQUE,
    PHONE VARCHAR2(14) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    AGE NUMBER NOT NULL,
    GENDER VARCHAR2(1) NOT NULL CHECK(GENDER IN('M', 'F')),
    PROFILE_IMG VARCHAR2(100),
    ENROLL_DATE DATE DEFAULT SYSDATE,
    KAKAO_LOGIN VARCHAR2(1) DEFAULT 'N' CHECK(KAKAO_LOGIN IN('N', 'Y')),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.NICKNAME IS '별칭';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.AGE IS '나이';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.PROFILE_IMG IS '프로필사진';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '가입일';
COMMENT ON COLUMN MEMBER.KAKAO_LOGIN IS '카카오계정';
COMMENT ON COLUMN MEMBER.STATUS IS '상태';

INSERT INTO MEMBER 
VALUES ('admin', '$2a$10$0ZZFnmV2fxN1JNAg1BSsx.kcLqQXMK6apchthmGiCETVsYG0DdAya', '관리자', '01000000000', 'admin@email.com', 0, 'F', 'resources/img/member/profile_img.png', DEFAULT, DEFAULT, DEFAULT);

INSERT INTO MEMBER 
VALUES ('user01', '$2a$10$CKY0j.HOti0nase1N3zWgu1TWQyV16N.v1mballOcVVWGy5aeWjBC', '유저1', '01011111111', 'user01@email.com', 20, 'M', 'resources/img/member/profile_img.png', DEFAULT, DEFAULT, DEFAULT);
--------------------------------------------------
--------------    REGION_CATEGORY	--------------
--------------------------------------------------

CREATE TABLE REGION_CATEGORY(
    REGION_NO NUMBER PRIMARY KEY,
    REGION_NAME VARCHAR2(100) NOT NULL
);

CREATE SEQUENCE SEQ_RCNO NOCACHE;

COMMENT ON COLUMN REGION_CATEGORY.REGION_NO IS '지역번호';
COMMENT ON COLUMN REGION_CATEGORY.REGION_NAME IS '지역명';

INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '서울');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '경기도');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '인천');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '대전');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '대구');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '광주');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '부산');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '울산');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '세종');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '강원');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '충북');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '충남');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '경북');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '경남');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '전북');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '전남');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '제주');
INSERT INTO REGION_CATEGORY VALUES(SEQ_RCNO.NEXTVAL, '전체지역');


-------------------- 피드 -------------------------

--------------------------------------------------
--------------    FEED_BOARD	------------------
--------------------------------------------------

CREATE TABLE FEED_BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_WRITER VARCHAR2(30) NOT NULL,
    REGION_NO NUMBER NOT NULL,
    BOARD_TYPE VARCHAR2(1) CHECK(BOARD_TYPE IN('G', 'M')), -- General : 일반, Meet : 모임
    BOARD_TITLE VARCHAR2(100) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    COUNT NUMBER DEFAULT 0,
    BOARD_DATE DATE DEFAULT SYSDATE,
    MEET_PLACE VARCHAR2(100),
    LONGITUDE VARCHAR2(100),
    LATITUDE VARCHAR2(100),
    MEET_DATE TIMESTAMP,
    MEET_TOTAL NUMBER,
    MEET_GENDER VARCHAR2(1) CHECK(MEET_GENDER IN('A', 'F', 'M')),
    MEET_AGE VARCHAR2(10),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER ON DELETE CASCADE,
    FOREIGN KEY(REGION_NO) REFERENCES REGION_CATEGORY ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_FBNO NOCACHE;

COMMENT ON COLUMN FEED_BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN FEED_BOARD.BOARD_WRITER IS '게시글작성자';
COMMENT ON COLUMN FEED_BOARD.REGION_NO IS '지역번호';
COMMENT ON COLUMN FEED_BOARD.BOARD_TYPE IS '게시글종류';
COMMENT ON COLUMN FEED_BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN FEED_BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN FEED_BOARD.COUNT IS '조회수';
COMMENT ON COLUMN FEED_BOARD.BOARD_DATE IS '작성일';
COMMENT ON COLUMN FEED_BOARD.MEET_PLACE IS '모임장소';
COMMENT ON COLUMN FEED_BOARD.LATITUDE IS '위도';
COMMENT ON COLUMN FEED_BOARD.LONGITUDE IS '경도';
COMMENT ON COLUMN FEED_BOARD.MEET_DATE IS '모임날짜';
COMMENT ON COLUMN FEED_BOARD.MEET_TOTAL IS '모집인원';
COMMENT ON COLUMN FEED_BOARD.MEET_GENDER IS '모집성별';
COMMENT ON COLUMN FEED_BOARD.MEET_AGE IS '모집나이';
COMMENT ON COLUMN FEED_BOARD.STATUS IS '게시글상태';

--------------------------------------------------
--------------    FEED_ATTACHMENT	--------------
--------------------------------------------------
CREATE TABLE FEED_ATTACHMENT(
    FILE_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(100) NOT NULL,
    CHANGE_NAME VARCHAR2(100) NOT NULL,
    FOREIGN KEY(BOARD_NO) REFERENCES FEED_BOARD ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_FANO NOCACHE;

COMMENT ON COLUMN FEED_ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN FEED_ATTACHMENT.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN FEED_ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN FEED_ATTACHMENT.CHANGE_NAME IS '파일수정명';

--------------------------------------------------
--------------    FEED_REPLY	------------------
--------------------------------------------------
CREATE TABLE FEED_REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    REPLY_WRITER VARCHAR2(30) NOT NULL,
    REPLY_CONTENT VARCHAR2(500),
    RGROUP NUMBER NOT NULL,
    RDEPTH NUMBER DEFAULT 0 CHECK(RDEPTH IN(0, 1)),
    REPLY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY(BOARD_NO) REFERENCES FEED_BOARD ON DELETE CASCADE,
    FOREIGN KEY(REPLY_WRITER) REFERENCES MEMBER ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_FRNO NOCACHE;

COMMENT ON COLUMN FEED_REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN FEED_REPLY.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN FEED_REPLY.REPLY_WRITER IS '댓글작성자';
COMMENT ON COLUMN FEED_REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN FEED_REPLY.RGROUP IS '댓글그룹';
COMMENT ON COLUMN FEED_REPLY.RDEPTH IS '댓글깊이';
COMMENT ON COLUMN FEED_REPLY.REPLY_DATE IS '작성일';
COMMENT ON COLUMN FEED_REPLY.STATUS IS '댓글상태';

--------------------------------------------------
--------------    FEED_LIKES 	------------------
--------------------------------------------------
CREATE TABLE FEED_LIKES(
    USER_ID VARCHAR2(30) NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    FOREIGN KEY(USER_ID) REFERENCES MEMBER ON DELETE CASCADE,
    FOREIGN KEY(BOARD_NO) REFERENCES FEED_BOARD ON DELETE CASCADE,
    PRIMARY KEY(USER_ID, BOARD_NO)
);

COMMENT ON COLUMN FEED_LIKES.USER_ID IS '회원아이디';
COMMENT ON COLUMN FEED_LIKES.BOARD_NO IS '게시글번호';


-------------------- 그룹 -------------------------

--------------------------------------------------
--------------    GROUP_CATEGORY    -------------- 
--------------------------------------------------
CREATE TABLE GROUP_CATEGORY(
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(20)
);

CREATE SEQUENCE SEQ_GCNO NOCACHE;

COMMENT ON COLUMN GROUP_CATEGORY.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN GROUP_CATEGORY.CATEGORY_NAME IS '카테고리명';

INSERT INTO GROUP_CATEGORY VALUES(SEQ_GCNO.NEXTVAL, '개발');
INSERT INTO GROUP_CATEGORY VALUES(SEQ_GCNO.NEXTVAL, '스터디');
INSERT INTO GROUP_CATEGORY VALUES(SEQ_GCNO.NEXTVAL, '운동/취미');
INSERT INTO GROUP_CATEGORY VALUES(SEQ_GCNO.NEXTVAL, '기타');

--------------------------------------------------
--------------      GROUP_ROOM   	-------------- 
--------------------------------------------------
CREATE TABLE GROUP_ROOM(
    GROUP_NO NUMBER PRIMARY KEY,
    REGION_NO NUMBER,
    CATEGORY_NO NUMBER NOT NULL,
    GROUP_NAME VARCHAR2(300) NOT NULL,
    GROUP_IMG VARCHAR2(100),
    GROUP_DETAIL VARCHAR2(4000) NOT NULL,
    GROUP_TYPE VARCHAR2(1) DEFAULT 'A' CHECK(GROUP_TYPE IN('A', 'B', 'C')),
    GROUP_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY(REGION_NO) REFERENCES REGION_CATEGORY ON DELETE CASCADE,
    FOREIGN KEY(CATEGORY_NO) REFERENCES GROUP_CATEGORY ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_GNO NOCACHE;

COMMENT ON COLUMN GROUP_ROOM.GROUP_NO IS '그룹방번호';
COMMENT ON COLUMN GROUP_ROOM.REGION_NO IS '지역번호';
COMMENT ON COLUMN GROUP_ROOM.CATEGORY_NO IS '카테고리번호';
COMMENT ON COLUMN GROUP_ROOM.GROUP_NAME IS '그룹명';
COMMENT ON COLUMN GROUP_ROOM.GROUP_IMG IS '그룹사진';
COMMENT ON COLUMN GROUP_ROOM.GROUP_DETAIL IS '그룹설명';
COMMENT ON COLUMN GROUP_ROOM.GROUP_TYPE IS '그룹방타입';
COMMENT ON COLUMN GROUP_ROOM.GROUP_DATE IS '생성일';

--------------------------------------------------
--------------    GROUP_MEMBER 	------------------
--------------------------------------------------
CREATE TABLE GROUP_MEMBER(
    GROUP_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    USER_RANK VARCHAR2(1) DEFAULT 'M' CHECK(USER_RANK IN('M', 'A')),
    FOREIGN KEY(GROUP_NO) REFERENCES GROUP_ROOM ON DELETE CASCADE,
    FOREIGN KEY(USER_ID) REFERENCES MEMBER ON DELETE CASCADE
);

COMMENT ON COLUMN GROUP_MEMBER.GROUP_NO IS '그룹방번호';
COMMENT ON COLUMN GROUP_MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN GROUP_MEMBER.USER_RANK IS '회원등급';

--------------------------------------------------
--------------    GROUP_JOIN_APPLY 	--------------
--------------------------------------------------
CREATE TABLE GROUP_JOIN_APPLY(
    APPLY_NO NUMBER PRIMARY KEY, 
    GROUP_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    GREETING VARCHAR2(500) NOT NULL,
    APPLY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY(GROUP_NO) REFERENCES GROUP_ROOM ON DELETE CASCADE,
    FOREIGN KEY(USER_ID) REFERENCES MEMBER ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_GJANO NOCACHE;

COMMENT ON COLUMN GROUP_JOIN_APPLY.APPLY_NO IS '신청번호';
COMMENT ON COLUMN GROUP_JOIN_APPLY.GROUP_NO IS '그룹방번호';
COMMENT ON COLUMN GROUP_JOIN_APPLY.USER_ID IS '회원아이디';
COMMENT ON COLUMN GROUP_JOIN_APPLY.GREETING IS '가입인사';
COMMENT ON COLUMN GROUP_JOIN_APPLY.STATUS IS '신청상태';

--------------------------------------------------
--------------    GROUP_CALENDAR 	--------------
--------------------------------------------------
CREATE TABLE GROUP_CALENDAR(
    CALENDAR_NO NUMBER PRIMARY KEY,
    GROUP_NO NUMBER NOT NULL,
    FOREIGN KEY(GROUP_NO) REFERENCES GROUP_ROOM ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_GCDNO NOCACHE;

COMMENT ON COLUMN GROUP_CALENDAR.CALENDAR_NO IS '캘린더번호';
COMMENT ON COLUMN GROUP_CALENDAR.GROUP_NO IS '그룹방번호';

--------------------------------------------------
--------------    CALENDAR_PLAN 	--------------
--------------------------------------------------
CREATE TABLE CALENDAR_PLAN(
    PLAN_NO NUMBER PRIMARY KEY,
    CALENDAR_NO NUMBER NOT NULL,
    USERID VARCHAR2(30) NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    MEMO VARCHAR2(500),
    START_DATE DATE DEFAULT SYSDATE,
    START_TIME TIMESTAMP DEFAULT SYSDATE,
    END_DATE DATE DEFAULT SYSDATE, -- SYSDATE 수정 필요
    END_TIME TIMESTAMP DEFAULT SYSDATE,
    COLOR VARCHAR2(30) NOT NULL,
    TEXT_COLOR VARCHAR2(30) NOT NULL,
    ALLDAY NUMBER NOT NULL,
    FOREIGN KEY(CALENDAR_NO) REFERENCES GROUP_CALENDAR ON DELETE CASCADE,
    FOREIGN KEY(USERID) REFERENCES MEMBER ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_PNO NOCACHE;

COMMENT ON COLUMN CALENDAR_PLAN.PLAN_NO IS '일정번호';
COMMENT ON COLUMN CALENDAR_PLAN.CALENDAR_NO IS '캘린더번호';
COMMENT ON COLUMN CALENDAR_PLAN.USERID IS '회원아이디';
COMMENT ON COLUMN CALENDAR_PLAN.TITLE IS '캘린더제목';
COMMENT ON COLUMN CALENDAR_PLAN.MEMO IS '캘린더메모';
COMMENT ON COLUMN CALENDAR_PLAN.START_DATE IS '시작날짜';
COMMENT ON COLUMN CALENDAR_PLAN.START_TIME IS '시작시간';
COMMENT ON COLUMN CALENDAR_PLAN.END_DATE IS '종료날짜';
COMMENT ON COLUMN CALENDAR_PLAN.END_DATE IS '종료시간';
COMMENT ON COLUMN CALENDAR_PLAN.COLOR IS '배경색';
COMMENT ON COLUMN CALENDAR_PLAN.TEXT_COLOR IS '글자색';
COMMENT ON COLUMN CALENDAR_PLAN.ALLDAY IS '하루종일 여부';

--------------------------------------------------
--------------    GROUP_BOARD 	------------------
--------------------------------------------------
CREATE TABLE GROUP_BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    GROUP_NO NUMBER NOT NULL,
    BOARD_WRITER VARCHAR2(30) NOT NULL,
    CALENDAR_NO NUMBER,
    BOARD_TITLE VARCHAR2(500) NOT NULL,
    BOARD_CONTENT VARCHAR2(4000) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE,
    COUNT NUMBER DEFAULT 0,
    BOARD_TYPE VARCHAR2(1) DEFAULT 'B' CHECK(BOARD_TYPE IN('B', 'N')),
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY(GROUP_NO) REFERENCES GROUP_ROOM ON DELETE CASCADE,
    FOREIGN KEY(BOARD_WRITER) REFERENCES MEMBER ON DELETE CASCADE,
    FOREIGN KEY(CALENDAR_NO) REFERENCES GROUP_CATEGORY ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_GBNO NOCACHE;

COMMENT ON COLUMN GROUP_BOARD.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN GROUP_BOARD.GROUP_NO IS '그룹방번호';
COMMENT ON COLUMN GROUP_BOARD.CALENDAR_NO IS '게시글작성자';
COMMENT ON COLUMN GROUP_BOARD.BOARD_WRITER IS '캘린더번호';
COMMENT ON COLUMN GROUP_BOARD.BOARD_TITLE IS '게시글제목';
COMMENT ON COLUMN GROUP_BOARD.BOARD_CONTENT IS '게시글내용';
COMMENT ON COLUMN GROUP_BOARD.CREATE_DATE IS '작성일';
COMMENT ON COLUMN GROUP_BOARD.COUNT IS '조회수';
COMMENT ON COLUMN GROUP_BOARD.BOARD_TYPE IS '게시글타입';
COMMENT ON COLUMN GROUP_BOARD.STATUS IS '게시글상태';

--------------------------------------------------
--------------    GROUP_LIKES 	------------------
--------------------------------------------------
CREATE TABLE GROUP_LIKES(
    USER_ID VARCHAR2(30) NOT NULL,
    BOARD_NO NUMBER NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES MEMBER ON DELETE CASCADE,
    FOREIGN KEY (BOARD_NO) REFERENCES GROUP_BOARD ON DELETE CASCADE,
    PRIMARY KEY(USER_ID, BOARD_NO)
);

COMMENT ON COLUMN GROUP_LIKES.USER_ID IS '회원아이디';
COMMENT ON COLUMN GROUP_LIKES.BOARD_NO IS '게시글번호';

--------------------------------------------------
--------------    GROUP_ATTACHMENT 	--------------
--------------------------------------------------
CREATE TABLE GROUP_ATTACHMENT(
    FILE_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    ORIGIN_NAME VARCHAR2(100) NOT NULL,
    CHANGE_NAME VARCHAR2(100) NOT NULL,
    FOREIGN KEY (BOARD_NO) REFERENCES GROUP_BOARD ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_GANO NOCACHE;

COMMENT ON COLUMN GROUP_ATTACHMENT.FILE_NO IS '파일번호';
COMMENT ON COLUMN GROUP_ATTACHMENT.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN GROUP_ATTACHMENT.ORIGIN_NAME IS '파일원본명';
COMMENT ON COLUMN GROUP_ATTACHMENT.CHANGE_NAME IS '파일수정명';

--------------------------------------------------
--------------    GROUP_REPLY 	------------------
--------------------------------------------------
CREATE TABLE GROUP_REPLY(
    REPLY_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    REPLY_WRITER VARCHAR2(30) NOT NULL,
    REPLY_CONTENT VARCHAR2(500),
    RGROUP NUMBER NOT NULL,
    RDEPTH NUMBER DEFAULT 0 CHECK(RDEPTH IN(0, 1)),
    REPLY_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N')),
    FOREIGN KEY(BOARD_NO) REFERENCES GROUP_BOARD ON DELETE CASCADE,
    FOREIGN KEY(REPLY_WRITER) REFERENCES MEMBER ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_GRNO NOCACHE;

COMMENT ON COLUMN GROUP_REPLY.REPLY_NO IS '댓글번호';
COMMENT ON COLUMN GROUP_REPLY.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN GROUP_REPLY.REPLY_WRITER IS '댓글작성자';
COMMENT ON COLUMN GROUP_REPLY.REPLY_CONTENT IS '댓글내용';
COMMENT ON COLUMN GROUP_REPLY.RGROUP IS '댓글그룹';
COMMENT ON COLUMN GROUP_REPLY.RDEPTH IS '댓글깊이';
COMMENT ON COLUMN GROUP_REPLY.REPLY_DATE IS '작성일';
COMMENT ON COLUMN GROUP_REPLY.STATUS IS '댓글상태';


---------------    채팅 관련     -------------------

--------------------------------------------------
--------------      CHAT_ROOM 	------------------
--------------------------------------------------
CREATE TABLE CHAT_ROOM(
    ROOM_NO NUMBER PRIMARY KEY,
    BOARD_NO NUMBER NOT NULL,
    ROOM_NAME VARCHAR2(100) NOT NULL,
    ROOM_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY(BOARD_NO) REFERENCES FEED_BOARD ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_CRNO NOCACHE;

COMMENT ON COLUMN CHAT_ROOM.ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT_ROOM.BOARD_NO IS '게시글번호';
COMMENT ON COLUMN CHAT_ROOM.ROOM_NAME IS '채팅방이름';
COMMENT ON COLUMN CHAT_ROOM.ROOM_DATE IS '생성일';

--------------------------------------------------
--------------      CHAT_MEMBER 	--------------
--------------------------------------------------
CREATE TABLE CHAT_MEMBER(
    ROOM_NO NUMBER NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL,
    USER_RANK VARCHAR2(1) DEFAULT 'M' CHECK(USER_RANK IN('A', 'M')),
    FOREIGN KEY(ROOM_NO) REFERENCES CHAT_ROOM ON DELETE CASCADE,
    FOREIGN KEY(USER_ID) REFERENCES MEMBER ON DELETE CASCADE,
    PRIMARY KEY(ROOM_NO, USER_ID)
);

COMMENT ON COLUMN CHAT_MEMBER.ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT_MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN CHAT_MEMBER.USER_RANK IS '회원등급';

--------------------------------------------------
--------------      CHAT 	----------------------
--------------------------------------------------
CREATE TABLE CHAT(
    CHAT_NO NUMBER PRIMARY KEY,
    ROOM_NO NUMBER NOT NULL,
    CHAT_WRITER VARCHAR2(30) NOT NULL,
    CHAT_CONTENT VARCHAR2(4000) NOT NULL,
    CHAT_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (ROOM_NO) REFERENCES CHAT_ROOM ON DELETE CASCADE,
    FOREIGN KEY (CHAT_WRITER) REFERENCES MEMBER ON DELETE CASCADE
);

CREATE SEQUENCE SEQ_CNO NOCACHE;

COMMENT ON COLUMN CHAT.CHAT_NO IS '채팅번호';
COMMENT ON COLUMN CHAT.ROOM_NO IS '채팅방번호';
COMMENT ON COLUMN CHAT.CHAT_WRITER IS '채팅작성자';
COMMENT ON COLUMN CHAT.CHAT_CONTENT IS '채팅내용';
COMMENT ON COLUMN CHAT.CHAT_DATE IS '작성일';


--------------------------------------------------
--------------     CERT 	----------------------
--------------------------------------------------
CREATE TABLE CERT(
    WHO VARCHAR2(30),
    SECRET VARCHAR2(6),
    WHEN DATE NOT NULL,
    PRIMARY KEY(WHO, SECRET)
);

--------------------------------------------------------------------------------


COMMIT;
